[workspace]
members = [
    "node",
    "runtime",
    "frame/appreciation",
    "frame/identity",
    "frame/identity/rpc",
    "frame/identity/rpc/runtime-api",
    "frame/reward",
    "primitives/rpc",
]
[profile.release]
panic = "unwind"
