use codec::Codec;
use sp_rpc::{Block as RpcBlock, BlockchainStats, GenesisData};

sp_api::decl_runtime_apis! {
	pub trait BlockInfoProvider<SignedBlock, AccountId, Hash>
	where
		SignedBlock: Codec,
		AccountId: Codec,
		Hash: Codec,
	{
		/// Provide additional information about `SignedBlock`
		///
		/// To use this method properly you need to specify block number at of `SignedBlock`
		/// this parameter will be automatically generated by `decl_runtime_apis!` macro
		fn get_block_info(block: SignedBlock) -> RpcBlock<AccountId, Hash>;

		/// Provide information about current blockchain state
		fn get_blockchain_data() -> BlockchainStats;

		/// Provide information about blockchain genesis config
		fn get_genesis_data() -> GenesisData<AccountId>;
	}
}
